CREATE TABLE IF NOT EXISTS Urls(
    short VARCHAR(16) NOT NULL PRIMARY KEY,
    url LONGTEXT NOT NULL,
    date_added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
) ENGINE=InnoDB DEFAULT CHARSET=ASCII;